server:
  port: 8081
  servlet:
    context-path: /swagger
spring:
  application:
    name: test-plugin-swagger
  main:
    allow-bean-definition-overriding: true
bubble:
  fireworks:
    swagger:
      enabled: true