server:
  port: 8082
spring:
  application:
    name: test-web
  swagger:
    enabled: true
  main:
    allow-bean-definition-overriding: true
bubble:
  fireworks:
    token:
      token-access-expire: 100
