server:
  port: 8083

spring:
  application:
    name: test-thread-pool

bubble:
  fireworks:
    dynamic:
      thread:
        pool[0]:
          contact: fxbin
          pool-name: test
          rejected-policy: DiscardPolicy
        pool[1]:
          contact: fxbin
          pool-name: test2222
          queue-type: ArrayBlockingQueue
          rejected-policy: RetryAndLogPolicy

